name: week_ops
on: 
  workflow_dispatch:

jobs:
  first-job:
    runs-on: windows-latest
    steps:
      # 1) Check out the repository so the workflow can access your files
      - name: Check out repo
        uses: actions/checkout@v3

      # 2) Set up Python (choose a version compatible with your script)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # (Optional) Install dependencies if you have a requirements.txt
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 3) Run your Python script (adjust path if it's in a subfolder)
      - name: Run Python script
        run: |
          python scripts/hello_world.py

      # 4) (Optional) Print or echo something else
      - name: Print goodbye
        run: echo "Goodbye"
